title: Project Hexagon
remote_theme: pmarsceill/just-the-docs

search_enabled: true
nav_enabled: true

aux_links:
  "GitHub Repository": "https://github.com/muskaanX/Hexagon"

include:
  - _includes
  - assets/css/style.css
