title: Project Hexagon
remote_theme: pmarsceill/just-the-docs

search_enabled: true
nav_enabled: true

aux_links:
  "GitHub Repository": "https://github.com/muskaanX/Hexagon"

# Include the SCSS file
include:
  - _sass/custom/custom.scss

sass:
  sass_dir: _sass

plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter
