title: Project Hexagon
remote_theme: pmarsceill/just-the-docs

search_enabled: true
nav_enabled: true

aux_links:
  "GitHub Repository": "https://github.com/muskaanX/Hexagon"

include:
  - _sass/custom/custom.scss

# Remove this block if not necessary
just_the_docs:
  aux_links:
    "Custom CSS":
      - assets/css/style.css
